spring:
  application:
    name: hackathon-video
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/hackathon-videos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  # Flyway Configuration
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    validate-migration-naming: true
    out-of-order: false
    ignore-migration-patterns: "*:missing,*:future"
    locations: classpath:db/migration
    clean-disabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: 8081

jwt:
  secret: postechHackathon2026SecretKey12345

aws:
  region: ${AWS_REGION:us-east-1}
  access-key-id: ${AWS_ACCESS_KEY_ID:test}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:test}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:hackathon-videos-bucket}

app:
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:video.processing.exchange}
    queue: ${RABBITMQ_QUEUE:video.processing.queue}
    routing-key: ${RABBITMQ_ROUTING_KEY:video.processing.routing}