# Configuração para ambiente local com LocalStack S3
spring:
  application:
    name: hackathon-video
  datasource:
    url: jdbc:mysql://localhost:3306/hackathon-videos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    validate-migration-naming: true
    out-of-order: false
    ignore-migration-patterns: "*:missing,*:future"
    locations: classpath:db/migration
    clean-disabled: true

server:
  port: 8081

jwt:
  secret: postechHackathon2026SecretKey12345

# Configuração LocalStack S3
aws:
  region: us-east-1
  access-key-id: test
  secret-access-key: test
  s3:
    bucket-name: hackathon-videos-bucket
    endpoint: http://localhost:4566

